// Codes d'action normalisés — valeur requêtable. La phrase française reste dans `justification`.
export const ACTION = {
  TIME_BLOCK_UPDATED: 'TIME_BLOCK_UPDATED',
  SCENARIO_CREATED: 'SCENARIO_CREATED',
  SCENARIO_APPLIED: 'SCENARIO_APPLIED',
  SCENARIO_ABANDONED: 'SCENARIO_ABANDONED',
  SCENARIO_FAILED: 'SCENARIO_FAILED',
  SCENARIO_REVERTED: 'SCENARIO_REVERTED',
  SCENARIO_REFUSED: 'SCENARIO_REFUSED',
  CONSTRAINT_VIOLATED: 'CONSTRAINT_VIOLATED',
  CONSTRAINT_RESOLVED: 'CONSTRAINT_RESOLVED',
  WORLD_RECALCULATED: 'WORLD_RECALCULATED',
  WORLD_SEEDED: 'WORLD_SEEDED',
  // People Graph — mêmes AuditEvents normalisés
  PERSON_CREATED: 'PERSON_CREATED',
  PERSON_UPDATED: 'PERSON_UPDATED',
  RSVP_CHANGED: 'RSVP_CHANGED',
  RELATION_CREATED: 'RELATION_CREATED',
  RELATION_REMOVED: 'RELATION_REMOVED',
  CONSTRAINT_CREATED: 'CONSTRAINT_CREATED',
  TABLE_ASSIGNMENT_CHANGED: 'TABLE_ASSIGNMENT_CHANGED',
  SOCIAL_CONFLICT_DETECTED: 'SOCIAL_CONFLICT_DETECTED',
  SOCIAL_GRAPH_SEEDED: 'SOCIAL_GRAPH_SEEDED',
  // Resource Graph — mêmes AuditEvents normalisés
  RESOURCE_CREATED: 'RESOURCE_CREATED',
  RESOURCE_CONFLICT_DETECTED: 'RESOURCE_CONFLICT_DETECTED',
  RESOURCE_GRAPH_SEEDED: 'RESOURCE_GRAPH_SEEDED',
  // Event Graph — mêmes AuditEvents normalisés
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_PERSON_ASSIGNED: 'EVENT_PERSON_ASSIGNED',
  EVENT_VENDOR_ASSIGNED: 'EVENT_VENDOR_ASSIGNED',
  EVENT_RESOURCE_ASSIGNED: 'EVENT_RESOURCE_ASSIGNED',
  EVENT_CONFLICT_DETECTED: 'EVENT_CONFLICT_DETECTED',
  EVENT_GRAPH_SEEDED: 'EVENT_GRAPH_SEEDED',
};

export async function logAudit(db, worldId, entry) {
  return db.AuditEvent.create({ world_id: worldId, ...entry });
}

export async function emitEvent(db, worldId, eventType, payload = {}, source = 'system', severity = 'info') {
  return db.SystemEvent.create({ world_id: worldId, event_type: eventType, payload, source, severity });
}