// Le Panthéon : les dimensions du World Model, incarnées.
// `line` = la phrase du chapitre. La fonction ne vient qu'après.
export const PANTHEON = [
  {
    key: 'gaia',
    name: 'GAÏA',
    line: "Un mariage n'est pas un planning. C'est un monde.",
    title: "Chef d'orchestre harmonique",
    manifesto: "Elle ne voit pas un planning. Elle voit un monde vivant : la terre, l'architecture, les personnes, la lumière et les événements appartiennent au même organisme.",
    innovation: 'World Model — une seule réalité, des milliers de relations.',
    role: 'Comprendre le monde qui compose votre mariage.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/c16c89b92_generated_image.png',
  },
  {
    key: 'zeus',
    name: 'ZEUS',
    line: "Voir de très haut n'oblige pas à perdre le détail.",
    title: "Le maître de l'orchestration globale",
    manifesto: "Une perspective presque divine sur votre mariage : les espaces, les invités, les services et le ciel forment une seule composition organisée.",
    innovation: 'Vue globale, supervision, gouvernance des décisions.',
    role: "Voir l'ensemble sans jamais perdre le détail.",
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/1bb65ccc3_generated_image.png',
  },
  {
    key: 'chronos',
    name: 'CHRONOS',
    line: "Une minute n'est jamais seulement une minute.",
    title: 'Le maître du temps',
    manifesto: "Le temps traverse physiquement votre mariage. Chaque minute déplacée se propage à travers tout ce qui suit.",
    innovation: 'Timeline, Time Blocks, marges, échéances, propagation temporelle.',
    role: "Comprendre qu'une minute n'est jamais seulement une minute.",
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/412d38aee_generated_image.png',
  },
  {
    key: 'poseidon',
    name: 'POSÉIDON',
    line: "L'émotion est une onde. Elle traverse la nuit entière.",
    title: 'Le maître des vagues sonores et émotionnelles',
    manifesto: "La musique, le son et la lumière ne décorent pas la soirée : ils la traversent, comme une onde.",
    innovation: 'Ambiance, immersion, continuité sensorielle.',
    role: "Faire tenir l'émotion d'un bout à l'autre de la nuit.",
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/081b27dfb_generated_image.png',
  },
  {
    key: 'athena',
    name: 'ATHÉNA',
    line: 'Elle ne devine pas. Elle vérifie.',
    title: 'Architecture intelligente & stratégie',
    manifesto: "L'architecture du mariage devient géométrie : contraintes, conflits, scénarios, décisions.",
    innovation: 'Constraint Engine, Conflict Engine, Scenario Engine.',
    role: 'Vérifier, simuler, résoudre.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/99d91540b_generated_image.png',
  },
  {
    key: 'aphrodite',
    name: 'APHRODITE',
    line: "La beauté n'est pas un supplément. C'est une dimension.",
    title: 'Scénographie & esthétique absolue',
    manifesto: "Fleurs, décoration, matières et atmosphère : la beauté n'est pas un supplément, c'est une dimension du monde.",
    innovation: 'Scénographie reliée aux ressources et aux lieux.',
    role: 'Tenir la promesse esthétique jusque dans la logistique.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/bc877a09d_generated_image.png',
  },
  {
    key: 'apollon',
    name: 'APOLLON',
    line: 'Un instant non photographié devient un instant perdu.',
    title: 'Lumière & créateurs de souvenirs',
    manifesto: "La photographie et la vidéo ne suivent pas le mariage : elles en dépendent, et le mariage dépend d'elles.",
    innovation: 'Prestataires image reliés au temps et aux moments clés.',
    role: 'Protéger les instants qui deviendront la mémoire.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/0724d83d6_generated_image.png',
  },
  {
    key: 'hermes',
    name: 'HERMÈS',
    line: "Une information perdue devient une décision impossible.",
    title: 'Le messager & la connexion instantanée',
    manifesto: "Mariés, familles et prestataires forment un réseau. L'information doit circuler sans se perdre.",
    innovation: 'Relations, documents, échanges, circulation de la vérité.',
    role: 'Relier ceux qui font le mariage.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/7a972ba64_generated_image.png',
  },
  {
    key: 'ares',
    name: 'ARÈS',
    line: 'Avant la première note, il y a des camions et des heures.',
    title: 'Puissance de régie & maîtrise du terrain',
    manifesto: "Avant la première note, il y a des camions, des structures et des heures. Le mariage naît sous vos yeux.",
    innovation: 'Montage, installation, transport, infrastructures.',
    role: 'Tenir le terrain, du premier câble au démontage.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/896d83a97_generated_image.png',
  },
  {
    key: 'demeter',
    name: 'DÉMÉTER',
    line: "Une ressource n'est pas une ligne budgétaire. C'est une matière vivante.",
    title: 'Art de la table & ressources durables',
    manifesto: "Gastronomie, terroir, partage : la ressource n'est pas une ligne budgétaire, c'est une matière vivante.",
    innovation: 'Resource Graph — capacités réelles, couverts, disponibilités.',
    role: 'Nourrir un monde entier, sans approximation.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/8105b673c_generated_image.png',
  },
  {
    key: 'artemis',
    name: 'ARTÉMIS',
    line: 'Les lieux extraordinaires imposent leurs propres lois.',
    title: 'Lieux sauvages & espaces insolites',
    manifesto: "Forêts, domaines, architectures abandonnées : les lieux extraordinaires imposent leurs propres lois.",
    innovation: 'Lieux, accès, contraintes spatiales et météorologiques.',
    role: "Rendre l'impossible praticable.",
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/4191b9103_generated_image.png',
  },
  {
    key: 'hephaistos',
    name: 'HÉPHAÏSTOS',
    line: "Chaque mariage exige des outils qui n'existent pas encore.",
    title: 'Forge numérique & sur-mesure technique',
    manifesto: "L'artisanat et la technologie se rencontrent : chaque mariage exige ses propres outils.",
    innovation: 'Moteur déterministe, interfaces sur-mesure, audit complet.',
    role: 'Forger ce qui n’existe pas encore.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/eaf170572_generated_image.png',
  },
  {
    key: 'dionysos',
    name: 'DIONYSOS',
    line: 'La nuit a ses propres lois.',
    title: 'Célébration & allégresse nocturne',
    manifesto: "La nuit a ses propres règles : énergie, mouvement, spectacle, et une mémoire qui se grave dans les corps.",
    innovation: 'Événements nocturnes, live, DJ, orchestration du spectacle.',
    role: 'Faire durer la nuit exactement le temps qu’il faut.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/fabae45d6_generated_image.png',
  },
  {
    key: 'hestia',
    name: 'HESTIA',
    line: "Un mariage est d'abord une continuité entre des générations.",
    title: 'Le foyer & le cercle intergénérationnel',
    manifesto: "Enfants, parents, grands-parents : un mariage est d'abord une continuité entre des générations.",
    innovation: 'People Graph — liens familiaux, accessibilité, contraintes humaines.',
    role: 'Prendre soin de ceux qui comptent.',
    image: 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/1951cd0c6_generated_image.png',
  },
];

export const HERO_IMAGE = 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/481aee1ca_generated_image.png';
export const CONVERGENCE_IMAGE = 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/ba47f39d0_generated_image.png';
export const COUPLE_IMAGE = 'https://media.base44.com/images/public/6a7b2973a480e55b3c82a63f/79b88a631_generated_image.png';